# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QSopj7t_8syc7DMb6aL2dv0yoqWfmd5H
"""

!pip install streamlit
!pip install pyngrok

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Install Streamlit if not already installed
!pip install streamlit

# Cargar datos
df = pd.read_csv("database_titanic.csv")

st.write("""
# Aplicación Streamlit – Análisis Titanic
### Unidad 3 – Taller de Programación II
""")

# Sidebar
with st.sidebar:
    st.write("## Opciones")
    div = st.slider("Número de bins:", 1, 20, 5)
    st.write("Bins =", div)

# --- GRÁFICO 1: Histograma de Edades ---
fig1, ax1 = plt.subplots()
ax1.hist(df["Age"], bins=div)
ax1.set_xlabel("Edad")
ax1.set_ylabel("Frecuencia")
ax1.set_title("Histograma de edades")
st.pyplot(fig1)

# --- GRÁFICO 2: Distribución por sexo ---
df_male = df[df["Sex"] == "male"]
df_female = df[df["Sex"] == "female"]
fig2, ax2 = plt.subplots()
ax2.bar(["Hombres", "Mujeres"], [len(df_male), len(df_female)])
ax2.set_title("Distribución de hombres y mujeres")
ax2.set_ylabel("Cantidad")
st.pyplot(fig2)


# Análisis de sobrevivientes por sexo
survivors = df.groupby("Sex")["Survived"].sum()

fig3, ax3 = plt.subplots()
ax3.bar(["Hombres", "Mujeres"], [survivors["male"], survivors["female"]])
ax3.set_title("Número de sobrevivientes por sexo")
ax3.set_ylabel("Cantidad de sobrevivientes")
st.pyplot(fig3)

# Tabla de muestra
st.write("## Muestra de datos")
st.table(df.head())